=== JamesTu-jtjt/patent-scraper-tool/example/PatentIsuRegSpecXMLA_041016/patent.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!--
	專利公報 DTD 
	Version:A103.1.0  2014-05-22  公報增修初版(整併發明/新型/設計3DTD)
 -->

<!ELEMENT tw-patent-grants (tw-patent-grant*)>
<!ATTLIST tw-patent-grants
	total-count CDATA #IMPLIED
>

<!ELEMENT tw-patent-grant (tw-bibliographic-data-grant, drawings* , claims*)>
<!ELEMENT tw-bibliographic-data-grant (volno, isuno,kindcode*, publication-reference, certificate-number, application-reference, classification-ipc*, classification-locarno*, parties, examiners?, priority-claims*, tw-bio-deposit* , invention-title, refs*, orefs*, application-publication-reference* )>

<!--卷數-->
<!ELEMENT volno (#PCDATA)>
<!--期別-->
<!ELEMENT isuno (#PCDATA)>
<!--Kind Code-->
<!ELEMENT kindcode (#PCDATA)>

<!--書目資料結構-->
<!ELEMENT publication-reference (document-id)>
<!ELEMENT document-id (country |  doc-number |  kind |  date)*>
<!--國別-->
<!ELEMENT country (#PCDATA)>
<!--號碼-->
<!ELEMENT doc-number (#PCDATA)>
<!--類型-->
<!ELEMENT kind (#PCDATA)>
<!--日期-->
<!ELEMENT date (#PCDATA)>

<!--證書號資料-->
<!ELEMENT certificate-number (document-id)>

<!--申請案號資料-->
<!ELEMENT application-reference (document-id)>

<!--IPC-->
<!ELEMENT classification-ipc (main-classification, further-classification*)>
<!--工業設計分類號-->
<!ELEMENT classification-locarno (main-classification, further-classification*)>
<!--主 IPC / 主分類號-->
<!ELEMENT main-classification (#PCDATA)>
<!--IPC 分類 / 其他分類號-->
<!ELEMENT further-classification (#PCDATA)>

<!--相關人員資料-->
<!ELEMENT parties (applicants , inventors , agents*)>

<!--審查人員(新型無此資訊)-->
<!ELEMENT examiners (examiner*)>
<!ELEMENT examiner (chinese-name)>

<!--人員資訊(資料結構)-->
<!ELEMENT addressbook (chinese-name, english-name?, address, english-country?, english-address?)>
<!--中文名稱-->
<!ELEMENT chinese-name (last-name , first-name)>
<!-- 姓 -->
<!ELEMENT last-name (#PCDATA | img )*>
<!-- 名 -->
<!ELEMENT first-name (#PCDATA | img)*>
<!--英文名稱-->
<!ELEMENT english-name (last-name , middle-name , first-name)>
<!--中間名-->
<!ELEMENT middle-name (#PCDATA)>
<!--地址-->
<!ELEMENT address (#PCDATA | img)*>
<!--英文國別-->
<!ELEMENT english-country (#PCDATA)>
<!--英文地址-->
<!ELEMENT english-address (#PCDATA)>

<!--申請人-->
<!ELEMENT applicants (applicant+)>
<!ELEMENT applicant (addressbook)>

<!-- 發明人 / 設計人 / 新型創作人-->
<!ELEMENT inventors (inventor+)>
<!ELEMENT inventor (addressbook)>

<!-- 代理人-->
<!ELEMENT agents (agent*)>
<!ELEMENT agent (addressbook)>

<!-- 參考文獻-專利資訊(新型無此資訊)-->
<!ELEMENT refs (ref*)>
<!ELEMENT ref (country, doc-number, kind)>
<!-- 參考文獻-非專利資訊(新型無此資訊)-->
<!ELEMENT orefs (oref*)>
<!ELEMENT oref (#PCDATA)>


<!-- 優先權-->
<!ELEMENT priority-claims (priority-claim*)>
<!ELEMENT priority-claim (country , doc-number , date)>

<!-- 生物材料寄存(設計無此資訊)(新型無此資訊)-->
<!ELEMENT tw-bio-deposit (bio-accno | date | depositary)*>
<!-- 生物材料寄存號碼(設計無此資訊)(新型無此資訊)-->
<!ELEMENT bio-accno (#PCDATA)>
<!-- 生物材料寄存機構(設計無此資訊)(新型無此資訊)-->
<!ELEMENT depositary (country*, text*)>

<!-- 發明名稱 / 設計名稱 / 新型名稱-->
<!ELEMENT invention-title (chinese-title , english-title)>
<!-- 發明中文名稱 / 設計中文名稱 / 新型中文名稱-->
<!ELEMENT chinese-title (#PCDATA | img | sub | sup)*>
<!-- 發明英文名稱 / 設計英文名稱 / 新型英文名稱-->
<!ELEMENT english-title (#PCDATA | sub | sup)*>

<!--公開案號資料(設計無此資訊)(新型無此資訊)-->
<!ELEMENT application-publication-reference (document-id*)>

<!--圖式-->
<!ELEMENT drawings (#PCDATA | i | sup | b | em | u | sub | figure | br | drawing-description  | img | strong | p | blockquote | div )*>
<!--圖式簡單說明-->
<!ELEMENT drawing-description (#PCDATA | i | sup | b | em | u | sub | figure | br   | img | strong | p | blockquote | div)*>

<!--申請權利範圍-->
<!ELEMENT claims (claim)*>
<!ELEMENT claim (#PCDATA | i | sup | b | em | u | sub | figure | br   | img | strong | p | blockquote | div)*>

<!-- 文字內容 -->
<!ELEMENT text (#PCDATA)>

<!-- 斜體 -->
<!ELEMENT i (#PCDATA | i | sup | b | em | u | sub | figure | br   | img | strong | p | blockquote | div | a)*>
<!-- 段落 -->
<!ELEMENT p (#PCDATA | i | sup | b | em | u | sub | figure | br   | img | strong | p | blockquote | div | a)*>
<!-- 圖檔 -->
<!ELEMENT figure (#PCDATA | i | sup | b | em | u | sub | figure | br   | img | strong | p | blockquote | div)*>
<!-- 圖檔 -->
<!ELEMENT img (#PCDATA | i | sup | b | em | u | sub | figure | br   | img | strong | p | blockquote | div)*>
<!-- 換行 -->
<!ELEMENT br (#PCDATA | i | sup | b | em | u | sub | figure | br   | img | strong | p | blockquote | div)*>
<!-- 強調 -->
<!ELEMENT em (#PCDATA | i | sup | b | em | u | sub | figure | br   | img | strong | p | blockquote | div)*>
<!-- 更強調 -->
<!ELEMENT strong (#PCDATA | i | sup | b | em | u | sub | figure | br   | img | strong | p | blockquote | div)*>
<!-- 底線 -->
<!ELEMENT u (#PCDATA | i | sup | b | em | u | sub | figure | br   | img | strong | p | blockquote | div)*>
<!-- 下標 -->
<!ELEMENT sub (#PCDATA | i | sup | b | em | u | sub | figure | br   | img | strong | p | blockquote | div)*>
<!-- 上標 -->
<!ELEMENT sup (#PCDATA | i | sup | b | em | u | sub | figure | br   | img | strong | p | blockquote | div)*>
<!-- 粗體 -->
<!ELEMENT b (#PCDATA | i | sup | b | em | u | sub | figure | br   | img | strong | p | blockquote | div)*>
<!-- 引述區段 -->
<!ELEMENT blockquote (#PCDATA | i | sup | b | em | u | sub | figure | br   | img | strong | p | blockquote | div)*>
<!-- 區塊 -->
<!ELEMENT div (#PCDATA | i | sup | b | em | u | sub | figure | br   | img | strong | p | blockquote | div)*>
<!-- 連結 -->
<!ELEMENT a (#PCDATA | i | figure | img | br | em | u | sub | sup | b | blockquote)*>
<!ATTLIST a
	href CDATA #IMPLIED
>

<!ATTLIST blockquote
	type CDATA #IMPLIED
	align CDATA #IMPLIED
    id CDATA  #IMPLIED
    dir CDATA  #IMPLIED
   style CDATA  #IMPLIED
   isabst CDATA #IMPLIED
>

<!ATTLIST div
	style CDATA #IMPLIED
	isabst CDATA #IMPLIED
>

<!ATTLIST agent
	sequence CDATA  #IMPLIED
	rep-type CDATA  #IMPLIED
	id CDATA #IMPLIED
>
<!ATTLIST applicant
	sequence CDATA  #IMPLIED
	app-type CDATA  #IMPLIED
	id CDATA  #IMPLIED
>
<!ATTLIST examiner
	sequence CDATA  #IMPLIED
	app-type CDATA  #IMPLIED
	id CDATA  #IMPLIED
>
<!ATTLIST application-reference
	appl-type CDATA  #IMPLIED
	id CDATA  #IMPLIED
>
<!ATTLIST claim
	id CDATA  #IMPLIED
	num CDATA  #IMPLIED
>
<!ATTLIST claims
	id CDATA  #IMPLIED
	num CDATA  #IMPLIED
>
<!ATTLIST drawing-description
	id CDATA  #IMPLIED
>
<!ATTLIST drawings
	id CDATA  #IMPLIED
	num CDATA  #IMPLIED
>
<!ATTLIST figure
	id CDATA  #IMPLIED
	num CDATA  #IMPLIED
	figure-labels CDATA  #IMPLIED
>
<!ATTLIST img
	align CDATA  #IMPLIED
	id CDATA #IMPLIED
	height CDATA  #IMPLIED
	width CDATA  #IMPLIED
	file CDATA  #IMPLIED
	alt CDATA  #IMPLIED
	img-content CDATA  #IMPLIED
	img-format CDATA  #IMPLIED
	orientation CDATA  #IMPLIED
	inline CDATA  #IMPLIED
	giffile CDATA  #IMPLIED
>
<!ATTLIST invention-title
	id CDATA #IMPLIED
>
<!ATTLIST inventor
	sequence CDATA  #IMPLIED
  app-type CDATA  #IMPLIED
  id CDATA #IMPLIED
>
<!ATTLIST p
	type CDATA #IMPLIED
	align CDATA #IMPLIED
    id CDATA  #IMPLIED
    dir CDATA  #IMPLIED
   style CDATA  #IMPLIED
   isabst CDATA #IMPLIED
   isneedindent CDATA #IMPLIED
>
<!ATTLIST tw-bibliographic-data-grant
	country CDATA  #IMPLIED
	id CDATA  #IMPLIED
>
<!ATTLIST tw-patent-grant
	file CDATA  #IMPLIED
	lang CDATA  #IMPLIED
	id CDATA  #IMPLIED
	dtd-version CDATA  #IMPLIED
>
<!ATTLIST chinese-name
	name-type CDATA  #IMPLIED
	id CDATA #IMPLIED
>
<!ATTLIST english-name
	name-type CDATA  #IMPLIED
	id CDATA #IMPLIED
>
<!ATTLIST priority-claim
	sequence CDATA  #IMPLIED
	id CDATA #IMPLIED
>
<!ATTLIST main-classification
	edition CDATA  #IMPLIED
  classification-value CDATA #IMPLIED
>
<!ATTLIST further-classification
	edition CDATA  #IMPLIED
  classification-value CDATA #IMPLIED
>
<!ATTLIST drawing-description
	id CDATA #IMPLIED
>

=== JamesTu-jtjt/patent-scraper-tool/example/PatentIsuRegSpecXMLA_041016/102301323.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE tw-patent-grant SYSTEM "patent.dtd">
<tw-patent-grant dtd-version="A103.1.0">
  <tw-bibliographic-data-grant>
    <volno>41</volno>
    <isuno>16</isuno>
    <kindcode>S</kindcode>
    <publication-reference>
      <document-id>
        <doc-number>D160743</doc-number>
        <kind />
        <date>103/06/01</date>
      </document-id>
    </publication-reference>
    <certificate-number>
      <document-id>
        <doc-number>D160743</doc-number>
        <kind />
        <date />
      </document-id>
    </certificate-number>
    <application-reference appl-type="design">
      <document-id>
        <doc-number>102301323</doc-number>
        <kind />
        <date>102/02/21</date>
      </document-id>
    </application-reference>
    <classification-locarno>
      <main-classification edition="9">02-01</main-classification>
    </classification-locarno>
    <parties>
      <applicants>
        <applicant sequence="1" app-type="applicant">
          <addressbook>
            <chinese-name name-type="">
              <last-name>陳瑞馨</last-name>
              <first-name></first-name>
            </chinese-name>
            <english-name name-type="">
              <last-name>CHEN, RUEY SHIN</last-name>
              <middle-name />
              <first-name />
            </english-name>
            <address>金門縣</address>
            <english-country>TW</english-country>
            <english-address>TW</english-address>
          </addressbook>
        </applicant>
      </applicants>
      <inventors>
        <inventor sequence="1" app-type="applicant">
          <addressbook>
            <chinese-name name-type="">
              <last-name>陳瑞馨</last-name>
              <first-name></first-name>
            </chinese-name>
            <english-name name-type="">
              <last-name>CHEN, RUEY SHIN</last-name>
              <middle-name></middle-name>
              <first-name></first-name>
            </english-name>
            <address></address>
            <english-country>TW</english-country>
            <english-address>TW</english-address>
          </addressbook>
        </inventor>
      </inventors>
      <agents></agents>
    </parties>
    <examiners>
      <examiner>
        <chinese-name>
          <last-name>陳慧媛</last-name>
          <first-name />
        </chinese-name>
      </examiner>
    </examiners>
    <priority-claims></priority-claims>
    <tw-bio-deposit></tw-bio-deposit>
    <invention-title>
      <chinese-title>褲子</chinese-title>
      <english-title />
    </invention-title>
    <refs>
      <ref>
        <country>US</country>
        <doc-number>D510791</doc-number>
        <kind></kind>
      </ref>
      <ref>
        <country>US</country>
        <doc-number>D603582</doc-number>
        <kind></kind>
      </ref>
    </refs>
    <application-publication-reference>
      <document-id>
        <doc-number></doc-number>
        <kind />
        <date></date>
      </document-id>
    </application-publication-reference>
  </tw-bibliographic-data-grant>
  <drawings num="">
    <figure>
      <img align="absmiddle" height="592px" width="492px" file="ed10001.JPG" alt="圖式IMG-2/Draw/ed10001.JPG" img-content="tif" img-format="tif" orientation="portrait" inline="yes"></img>
    </figure>
    <figure>
      <img align="absmiddle" height="482px" width="475px" file="ed10002.JPG" alt="圖式IMG-2/Draw/ed10002.JPG" img-content="tif" img-format="tif" orientation="portrait" inline="yes"></img>
    </figure>
    <figure>
      <img align="absmiddle" height="433px" width="493px" file="ed10003.JPG" alt="圖式IMG-2/Draw/ed10003.JPG" img-content="tif" img-format="tif" orientation="portrait" inline="yes"></img>
    </figure>
    <figure>
      <img align="absmiddle" height="350px" width="582px" file="ed10004.JPG" alt="圖式IMG-2/Draw/ed10004.JPG" img-content="tif" img-format="tif" orientation="portrait" inline="yes"></img>
    </figure>
    <figure>
      <img align="absmiddle" height="386px" width="589px" file="ed10005.JPG" alt="圖式IMG-2/Draw/ed10005.JPG" img-content="tif" img-format="tif" orientation="portrait" inline="yes"></img>
    </figure>
    <drawing-description>
      <p type="p">
        <p>本設計之特點在於其包括有：一件防漏褲子體(前視圖)是由防漏布料製造，並含有橢圓船型開口之排洩物承載袋(後視圖)、經由三向拉開之防漏拉鍊，即可方便地更換電子偵測裝置，尿布或尿片型之排洩物收集袋(使用狀態圖)。圖示所揭露之色彩為本案不主張之部分。
</p>
      </p>
      <p type="p">
        <p>1.因本設計為衣褲類，故只提供前視圖、使用狀態圖與後視圖與前視立體圖及後視立體圖，並省略其它視圖。
</p>
      </p>
    </drawing-description>
  </drawings>
  <claims />
</tw-patent-grant>

=== JamesTu-jtjt/patent-scraper-tool/example/PatentIsuRegSpecXMLA_041016/101116680.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE tw-patent-grant SYSTEM "patent.dtd">
<tw-patent-grant dtd-version="A103.1.0">
  <tw-bibliographic-data-grant>
    <volno>41</volno>
    <isuno>16</isuno>
    <kindcode>B</kindcode>
    <publication-reference>
      <document-id>
        <doc-number>I439543</doc-number>
        <kind />
        <date>103/06/01</date>
      </document-id>
    </publication-reference>
    <certificate-number>
      <document-id>
        <doc-number>I439543</doc-number>
        <kind />
        <date />
      </document-id>
    </certificate-number>
    <application-reference appl-type="invention">
      <document-id>
        <doc-number>101116680</doc-number>
        <kind />
        <date>101/05/10</date>
      </document-id>
    </application-reference>
    <classification-ipc>
      <main-classification edition="200601120140421V">C12N1/14</main-classification>
      <further-classification edition="200601120140421V">A01G1/04</further-classification>
    </classification-ipc>
    <parties>
      <applicants>
        <applicant sequence="1" app-type="applicant">
          <addressbook>
            <chinese-name name-type="">
              <last-name>慧普生技股份有限公司</last-name>
              <first-name></first-name>
            </chinese-name>
            <english-name name-type="">
              <last-name>WE-PRO BIOTECH CO., LTD.</last-name>
              <middle-name />
              <first-name />
            </english-name>
            <address>高雄市</address>
            <english-country>TW</english-country>
            <english-address>TW</english-address>
          </addressbook>
        </applicant>
      </applicants>
      <inventors>
        <inventor sequence="1" app-type="applicant">
          <addressbook>
            <chinese-name name-type="">
              <last-name>顏宏愷</last-name>
              <first-name></first-name>
            </chinese-name>
            <english-name name-type="">
              <last-name>YEN, HUNG KAI</last-name>
              <middle-name></middle-name>
              <first-name></first-name>
            </english-name>
            <address></address>
            <english-country>TW</english-country>
            <english-address>TW</english-address>
          </addressbook>
        </inventor>
        <inventor sequence="2" app-type="applicant">
          <addressbook>
            <chinese-name name-type="">
              <last-name>戴瑞凡</last-name>
              <first-name></first-name>
            </chinese-name>
            <english-name name-type="">
              <last-name>TAI, JUI FAN</last-name>
              <middle-name></middle-name>
              <first-name></first-name>
            </english-name>
            <address></address>
            <english-country>TW</english-country>
            <english-address>TW</english-address>
          </addressbook>
        </inventor>
        <inventor sequence="3" app-type="applicant">
          <addressbook>
            <chinese-name name-type="">
              <last-name>賈銅安</last-name>
              <first-name></first-name>
            </chinese-name>
            <english-name name-type="">
              <last-name>CHIA, TUNG AN</last-name>
              <middle-name></middle-name>
              <first-name></first-name>
            </english-name>
            <address></address>
            <english-country>TW</english-country>
            <english-address>TW</english-address>
          </addressbook>
        </inventor>
        <inventor sequence="4" app-type="applicant">
          <addressbook>
            <chinese-name name-type="">
              <last-name>賈鐵安</last-name>
              <first-name></first-name>
            </chinese-name>
            <english-name name-type="">
              <last-name>CHIA, TIEH AN</last-name>
              <middle-name></middle-name>
              <first-name></first-name>
            </english-name>
            <address></address>
            <english-country>TW</english-country>
            <english-address>TW</english-address>
          </addressbook>
        </inventor>
      </inventors>
      <agents>
        <agent sequence="1" rep-type="agent">
          <addressbook>
            <chinese-name name-type="">
              <last-name>陳啟舜</last-name>
              <first-name></first-name>
            </chinese-name>
            <address>高雄市</address>
          </addressbook>
        </agent>
      </agents>
    </parties>
    <examiners>
      <examiner>
        <chinese-name>
          <last-name>施雅儀</last-name>
          <first-name />
        </chinese-name>
      </examiner>
    </examiners>
    <priority-claims></priority-claims>
    <tw-bio-deposit></tw-bio-deposit>
    <invention-title>
      <chinese-title>牛樟芝的培養方法</chinese-title>
      <english-title>CULTIVATION METHOD OF TAIWANOFUNGUS CAMPHORATES</english-title>
    </invention-title>
    <refs>
      <ref>
        <country>CN</country>
        <doc-number>101151957</doc-number>
        <kind>A</kind>
      </ref>
      <ref>
        <country>CN</country>
        <doc-number>101822170</doc-number>
        <kind>A</kind>
      </ref>
    </refs>
    <orefs>
      <oref>林葦郁, "利用固定化菌體進行樟芝(Antrodia camphorata)的深層培養生產菌體代謝物之研究", 東海大學食品科學系研究所論文, 2005年                                                                                                                                                                                                                                                                                                                                   
</oref>
    </orefs>
    <application-publication-reference>
      <document-id>
        <doc-number>201346027</doc-number>
        <kind />
        <date>102/11/16</date>
      </document-id>
    </application-publication-reference>
  </tw-bibliographic-data-grant>
  <drawings num="第1圖 ">
    <figure>
      <img align="absmiddle" height="538px" width="426px" file="d10001.TIF" alt="*圖式ed10001.png" img-content="tif" img-format="tif" orientation="portrait" inline="yes" giffile="ed10001.png"></img>
    </figure>
    <figure>
      <img align="absmiddle" height="423px" width="299px" file="d10002.TIF" alt="圖式ed10002.png" img-content="tif" img-format="tif" orientation="portrait" inline="yes" giffile="ed10002.png"></img>
    </figure>
    <figure>
      <img align="absmiddle" height="451px" width="279px" file="d10003.TIF" alt="圖式ed10003.png" img-content="tif" img-format="tif" orientation="portrait" inline="yes" giffile="ed10003.png"></img>
    </figure>
    <figure>
      <img align="absmiddle" height="432px" width="251px" file="d10004.TIF" alt="圖式ed10004.png" img-content="tif" img-format="tif" orientation="portrait" inline="yes" giffile="ed10004.png"></img>
    </figure>
    <figure>
      <img align="absmiddle" height="425px" width="273px" file="d10005.TIF" alt="圖式ed10005.png" img-content="tif" img-format="tif" orientation="portrait" inline="yes" giffile="ed10005.png"></img>
    </figure>
    <figure>
      <img align="absmiddle" height="464px" width="321px" file="d10006.TIF" alt="圖式ed10006.png" img-content="tif" img-format="tif" orientation="portrait" inline="yes" giffile="ed10006.png"></img>
    </figure>
    <figure>
      <img align="absmiddle" height="603px" width="427px" file="d10007.TIF" alt="圖式ed10007.png" img-content="tif" img-format="tif" orientation="portrait" inline="yes" giffile="ed10007.png"></img>
    </figure>
    <figure>
      <img align="absmiddle" height="550px" width="906px" file="d10008.TIF" alt="圖式ed10008.png" img-content="tif" img-format="tif" orientation="portrait" inline="yes" giffile="ed10008.png"></img>
    </figure>
    <figure>
      <img align="absmiddle" height="521px" width="905px" file="d10009.TIF" alt="圖式ed10009.png" img-content="tif" img-format="tif" orientation="portrait" inline="yes" giffile="ed10009.png"></img>
    </figure>
    <drawing-description>
      <p type="p">第1圖：本發明牛樟芝的培養方法之步驟方塊圖(一)。</p>
      <p type="p">第2a圖：本實施例之柱體培養基的立體外觀圖-四面柱體。</p>
      <p type="p">第2b圖：本實施例之柱體培養基的立體外觀圖-六面柱體。</p>
      <p type="p">第2c圖：本實施例之柱體培養基的立體外觀圖-八面柱體。</p>
      <p type="p">第2d圖：本實施例之柱體培養基的立體外觀圖-十二面柱體。</p>
      <p type="p">第2e圖：本實施例之柱體培養基的立體外觀圖-圓柱體。</p>
      <p type="p">第3圖：本發明牛樟芝的培養方法之步驟方塊圖(二)。</p>
      <p type="p">第4圖：本實施例之UPLC-MS/MS層析圖([m/z]<sup>+</sup>
)。</p>
      <p type="p">第5圖：本實施例之UPLC-MS/MS層析圖([m/z]<sup>-</sup>
)。</p>
    </drawing-description>
  </drawings>
  <claims>
    <claim id="clm1" num="1">
      <p type="claim-text">一種牛樟芝的培養方法，其包含：一培養基配製步驟，係將重量百分比為0.1~50%之葡萄糖、1~5%之蛋白腖、0.1~50%之大麥萃取物、0.1~50%之酵母萃取物及0.5~10%之固化劑，以水配製成一混合溶液，將該混合溶液煮沸，使上述成分完全溶解後，使該混合溶液凝固成一柱體培養基，該柱體培養基之深度為2~20公分；一接種步驟，係於該柱體培養基之內部設有數個預定接種位，該數個預定接種位距離該柱體培養基之外表面0.5~10公分深處，將牛樟芝接種於各預定接種位上；及一培養步驟，係將接種完成之柱體培養基於溫度23~28℃之環境下培養至少三個月，獲得一牛樟菌體。</p>
    </claim>
    <claim id="clm2" num="2">
      <p type="claim-text">如申請專利範圍第1項所述之牛樟芝的培養方法，其中，該培養步驟後，更包含一乾燥步驟，係將長有牛樟菌體之柱體培養基，於30~40℃下烘乾至含水量低於2%，獲得一牛樟乾燥菌塊。</p>
    </claim>
    <claim id="clm3" num="3">
      <p type="claim-text">如申請專利範圍第1或2項所述之牛樟芝的培養方法，其中，各預定接種位之間相距0.5~2公分。</p>
    </claim>
    <claim id="clm4" num="4">
      <p type="claim-text">如申請專利範圍第3項所述之牛樟芝的培養方法，其中，該柱體培養基為多面柱體或圓柱體。</p>
    </claim>
    <claim id="clm5" num="5">
      <p type="claim-text">如申請專利範圍第1或2項所述之牛樟芝的培養方法，其中，該固化劑為瓊脂。</p>
    </claim>
    <claim id="clm6" num="6">
      <p type="claim-text">如申請專利範圍第1或2項所述之牛樟芝的培養方法，其中，該培養步驟之培養時間為4~12個月。</p>
    </claim>
    <claim id="clm7" num="7">
      <p type="claim-text">如申請專利範圍第2項所述之牛樟芝的培養方法，其中，該乾燥步驟之乾燥時間為24~72小時。</p>
    </claim>
  </claims>
</tw-patent-grant>
