=== JamesTu-jtjt/patent-scraper-tool/example/PatentIsuRegSpecXMLA_041016/patent.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!--
	專利公報 DTD 
	Version:A103.1.0  2014-05-22  公報增修初版(整併發明/新型/設計3DTD)
 -->

<!ELEMENT tw-patent-grants (tw-patent-grant*)>
<!ATTLIST tw-patent-grants
	total-count CDATA #IMPLIED
>

<!ELEMENT tw-patent-grant (tw-bibliographic-data-grant, drawings* , claims*)>
<!ELEMENT tw-bibliographic-data-grant (volno, isuno,kindcode*, publication-reference, certificate-number, application-reference, classification-ipc*, classification-locarno*, parties, examiners?, priority-claims*, tw-bio-deposit* , invention-title, refs*, orefs*, application-publication-reference* )>

<!--卷數-->
<!ELEMENT volno (#PCDATA)>
<!--期別-->
<!ELEMENT isuno (#PCDATA)>
<!--Kind Code-->
<!ELEMENT kindcode (#PCDATA)>

<!--書目資料結構-->
<!ELEMENT publication-reference (document-id)>
<!ELEMENT document-id (country |  doc-number |  kind |  date)*>
<!--國別-->
<!ELEMENT country (#PCDATA)>
<!--號碼-->
<!ELEMENT doc-number (#PCDATA)>
<!--類型-->
<!ELEMENT kind (#PCDATA)>
<!--日期-->
<!ELEMENT date (#PCDATA)>

<!--證書號資料-->
<!ELEMENT certificate-number (document-id)>

<!--申請案號資料-->
<!ELEMENT application-reference (document-id)>

<!--IPC-->
<!ELEMENT classification-ipc (main-classification, further-classification*)>
<!--工業設計分類號-->
<!ELEMENT classification-locarno (main-classification, further-classification*)>
<!--主 IPC / 主分類號-->
<!ELEMENT main-classification (#PCDATA)>
<!--IPC 分類 / 其他分類號-->
<!ELEMENT further-classification (#PCDATA)>

<!--相關人員資料-->
<!ELEMENT parties (applicants , inventors , agents*)>

<!--審查人員(新型無此資訊)-->
<!ELEMENT examiners (examiner*)>
<!ELEMENT examiner (chinese-name)>

<!--人員資訊(資料結構)-->
<!ELEMENT addressbook (chinese-name, english-name?, address, english-country?, english-address?)>
<!--中文名稱-->
<!ELEMENT chinese-name (last-name , first-name)>
<!-- 姓 -->
<!ELEMENT last-name (#PCDATA | img )*>
<!-- 名 -->
<!ELEMENT first-name (#PCDATA | img)*>
<!--英文名稱-->
<!ELEMENT english-name (last-name , middle-name , first-name)>
<!--中間名-->
<!ELEMENT middle-name (#PCDATA)>
<!--地址-->
<!ELEMENT address (#PCDATA | img)*>
<!--英文國別-->
<!ELEMENT english-country (#PCDATA)>
<!--英文地址-->
<!ELEMENT english-address (#PCDATA)>

<!--申請人-->
<!ELEMENT applicants (applicant+)>
<!ELEMENT applicant (addressbook)>

<!-- 發明人 / 設計人 / 新型創作人-->
<!ELEMENT inventors (inventor+)>
<!ELEMENT inventor (addressbook)>

<!-- 代理人-->
<!ELEMENT agents (agent*)>
<!ELEMENT agent (addressbook)>

<!-- 參考文獻-專利資訊(新型無此資訊)-->
<!ELEMENT refs (ref*)>
<!ELEMENT ref (country, doc-number, kind)>
<!-- 參考文獻-非專利資訊(新型無此資訊)-->
<!ELEMENT orefs (oref*)>
<!ELEMENT oref (#PCDATA)>


<!-- 優先權-->
<!ELEMENT priority-claims (priority-claim*)>
<!ELEMENT priority-claim (country , doc-number , date)>

<!-- 生物材料寄存(設計無此資訊)(新型無此資訊)-->
<!ELEMENT tw-bio-deposit (bio-accno | date | depositary)*>
<!-- 生物材料寄存號碼(設計無此資訊)(新型無此資訊)-->
<!ELEMENT bio-accno (#PCDATA)>
<!-- 生物材料寄存機構(設計無此資訊)(新型無此資訊)-->
<!ELEMENT depositary (country*, text*)>

<!-- 發明名稱 / 設計名稱 / 新型名稱-->
<!ELEMENT invention-title (chinese-title , english-title)>
<!-- 發明中文名稱 / 設計中文名稱 / 新型中文名稱-->
<!ELEMENT chinese-title (#PCDATA | img | sub | sup)*>
<!-- 發明英文名稱 / 設計英文名稱 / 新型英文名稱-->
<!ELEMENT english-title (#PCDATA | sub | sup)*>

<!--公開案號資料(設計無此資訊)(新型無此資訊)-->
<!ELEMENT application-publication-reference (document-id*)>

<!--圖式-->
<!ELEMENT drawings (#PCDATA | i | sup | b | em | u | sub | figure | br | drawing-description  | img | strong | p | blockquote | div )*>
<!--圖式簡單說明-->
<!ELEMENT drawing-description (#PCDATA | i | sup | b | em | u | sub | figure | br   | img | strong | p | blockquote | div)*>

<!--申請權利範圍-->
<!ELEMENT claims (claim)*>
<!ELEMENT claim (#PCDATA | i | sup | b | em | u | sub | figure | br   | img | strong | p | blockquote | div)*>

<!-- 文字內容 -->
<!ELEMENT text (#PCDATA)>

<!-- 斜體 -->
<!ELEMENT i (#PCDATA | i | sup | b | em | u | sub | figure | br   | img | strong | p | blockquote | div | a)*>
<!-- 段落 -->
<!ELEMENT p (#PCDATA | i | sup | b | em | u | sub | figure | br   | img | strong | p | blockquote | div | a)*>
<!-- 圖檔 -->
<!ELEMENT figure (#PCDATA | i | sup | b | em | u | sub | figure | br   | img | strong | p | blockquote | div)*>
<!-- 圖檔 -->
<!ELEMENT img (#PCDATA | i | sup | b | em | u | sub | figure | br   | img | strong | p | blockquote | div)*>
<!-- 換行 -->
<!ELEMENT br (#PCDATA | i | sup | b | em | u | sub | figure | br   | img | strong | p | blockquote | div)*>
<!-- 強調 -->
<!ELEMENT em (#PCDATA | i | sup | b | em | u | sub | figure | br   | img | strong | p | blockquote | div)*>
<!-- 更強調 -->
<!ELEMENT strong (#PCDATA | i | sup | b | em | u | sub | figure | br   | img | strong | p | blockquote | div)*>
<!-- 底線 -->
<!ELEMENT u (#PCDATA | i | sup | b | em | u | sub | figure | br   | img | strong | p | blockquote | div)*>
<!-- 下標 -->
<!ELEMENT sub (#PCDATA | i | sup | b | em | u | sub | figure | br   | img | strong | p | blockquote | div)*>
<!-- 上標 -->
<!ELEMENT sup (#PCDATA | i | sup | b | em | u | sub | figure | br   | img | strong | p | blockquote | div)*>
<!-- 粗體 -->
<!ELEMENT b (#PCDATA | i | sup | b | em | u | sub | figure | br   | img | strong | p | blockquote | div)*>
<!-- 引述區段 -->
<!ELEMENT blockquote (#PCDATA | i | sup | b | em | u | sub | figure | br   | img | strong | p | blockquote | div)*>
<!-- 區塊 -->
<!ELEMENT div (#PCDATA | i | sup | b | em | u | sub | figure | br   | img | strong | p | blockquote | div)*>
<!-- 連結 -->
<!ELEMENT a (#PCDATA | i | figure | img | br | em | u | sub | sup | b | blockquote)*>
<!ATTLIST a
	href CDATA #IMPLIED
>

<!ATTLIST blockquote
	type CDATA #IMPLIED
	align CDATA #IMPLIED
    id CDATA  #IMPLIED
    dir CDATA  #IMPLIED
   style CDATA  #IMPLIED
   isabst CDATA #IMPLIED
>

<!ATTLIST div
	style CDATA #IMPLIED
	isabst CDATA #IMPLIED
>

<!ATTLIST agent
	sequence CDATA  #IMPLIED
	rep-type CDATA  #IMPLIED
	id CDATA #IMPLIED
>
<!ATTLIST applicant
	sequence CDATA  #IMPLIED
	app-type CDATA  #IMPLIED
	id CDATA  #IMPLIED
>
<!ATTLIST examiner
	sequence CDATA  #IMPLIED
	app-type CDATA  #IMPLIED
	id CDATA  #IMPLIED
>
<!ATTLIST application-reference
	appl-type CDATA  #IMPLIED
	id CDATA  #IMPLIED
>
<!ATTLIST claim
	id CDATA  #IMPLIED
	num CDATA  #IMPLIED
>
<!ATTLIST claims
	id CDATA  #IMPLIED
	num CDATA  #IMPLIED
>
<!ATTLIST drawing-description
	id CDATA  #IMPLIED
>
<!ATTLIST drawings
	id CDATA  #IMPLIED
	num CDATA  #IMPLIED
>
<!ATTLIST figure
	id CDATA  #IMPLIED
	num CDATA  #IMPLIED
	figure-labels CDATA  #IMPLIED
>
<!ATTLIST img
	align CDATA  #IMPLIED
	id CDATA #IMPLIED
	height CDATA  #IMPLIED
	width CDATA  #IMPLIED
	file CDATA  #IMPLIED
	alt CDATA  #IMPLIED
	img-content CDATA  #IMPLIED
	img-format CDATA  #IMPLIED
	orientation CDATA  #IMPLIED
	inline CDATA  #IMPLIED
	giffile CDATA  #IMPLIED
>
<!ATTLIST invention-title
	id CDATA #IMPLIED
>
<!ATTLIST inventor
	sequence CDATA  #IMPLIED
  app-type CDATA  #IMPLIED
  id CDATA #IMPLIED
>
<!ATTLIST p
	type CDATA #IMPLIED
	align CDATA #IMPLIED
    id CDATA  #IMPLIED
    dir CDATA  #IMPLIED
   style CDATA  #IMPLIED
   isabst CDATA #IMPLIED
   isneedindent CDATA #IMPLIED
>
<!ATTLIST tw-bibliographic-data-grant
	country CDATA  #IMPLIED
	id CDATA  #IMPLIED
>
<!ATTLIST tw-patent-grant
	file CDATA  #IMPLIED
	lang CDATA  #IMPLIED
	id CDATA  #IMPLIED
	dtd-version CDATA  #IMPLIED
>
<!ATTLIST chinese-name
	name-type CDATA  #IMPLIED
	id CDATA #IMPLIED
>
<!ATTLIST english-name
	name-type CDATA  #IMPLIED
	id CDATA #IMPLIED
>
<!ATTLIST priority-claim
	sequence CDATA  #IMPLIED
	id CDATA #IMPLIED
>
<!ATTLIST main-classification
	edition CDATA  #IMPLIED
  classification-value CDATA #IMPLIED
>
<!ATTLIST further-classification
	edition CDATA  #IMPLIED
  classification-value CDATA #IMPLIED
>
<!ATTLIST drawing-description
	id CDATA #IMPLIED
>

=== JamesTu-jtjt/patent-scraper-tool/example/PatentIsuRegSpecXMLA_041016/102305373.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE tw-patent-grant SYSTEM "patent.dtd">
<tw-patent-grant dtd-version="A103.1.0">
  <tw-bibliographic-data-grant>
    <volno>41</volno>
    <isuno>16</isuno>
    <kindcode>S</kindcode>
    <publication-reference>
      <document-id>
        <doc-number>D160744</doc-number>
        <kind />
        <date>103/06/01</date>
      </document-id>
    </publication-reference>
    <certificate-number>
      <document-id>
        <doc-number>D160744</doc-number>
        <kind />
        <date />
      </document-id>
    </certificate-number>
    <application-reference appl-type="design">
      <document-id>
        <doc-number>102305373</doc-number>
        <kind />
        <date>102/08/08</date>
      </document-id>
    </application-reference>
    <classification-locarno>
      <main-classification edition="9">02-03</main-classification>
    </classification-locarno>
    <parties>
      <applicants>
        <applicant sequence="1" app-type="applicant">
          <addressbook>
            <chinese-name name-type="">
              <last-name>黃詩銓</last-name>
              <first-name></first-name>
            </chinese-name>
            <english-name name-type="">
              <last-name></last-name>
              <middle-name />
              <first-name />
            </english-name>
            <address>新北市</address>
            <english-country>TW</english-country>
            <english-address>TW</english-address>
          </addressbook>
        </applicant>
      </applicants>
      <inventors>
        <inventor sequence="1" app-type="applicant">
          <addressbook>
            <chinese-name name-type="">
              <last-name>黃詩銓</last-name>
              <first-name></first-name>
            </chinese-name>
            <english-name name-type="">
              <last-name></last-name>
              <middle-name></middle-name>
              <first-name></first-name>
            </english-name>
            <address></address>
            <english-country>TW</english-country>
            <english-address>TW</english-address>
          </addressbook>
        </inventor>
      </inventors>
      <agents></agents>
    </parties>
    <examiners>
      <examiner>
        <chinese-name>
          <last-name>陳慧媛</last-name>
          <first-name />
        </chinese-name>
      </examiner>
    </examiners>
    <priority-claims></priority-claims>
    <tw-bio-deposit></tw-bio-deposit>
    <invention-title>
      <chinese-title>安全帽（一）</chinese-title>
      <english-title />
    </invention-title>
    <refs>
      <ref>
        <country>TW</country>
        <doc-number>D151747</doc-number>
        <kind></kind>
      </ref>
    </refs>
    <application-publication-reference>
      <document-id>
        <doc-number></doc-number>
        <kind />
        <date></date>
      </document-id>
    </application-publication-reference>
  </tw-bibliographic-data-grant>
  <drawings num="">
    <figure>
      <img align="absmiddle" height="562px" width="698px" file="ed10001.JPG" alt="圖式IMG-2/Draw/ed10001.JPG" img-content="tif" img-format="tif" orientation="portrait" inline="yes"></img>
    </figure>
    <figure>
      <img align="absmiddle" height="598px" width="694px" file="ed10002.JPG" alt="圖式IMG-2/Draw/ed10002.JPG" img-content="tif" img-format="tif" orientation="portrait" inline="yes"></img>
    </figure>
    <figure>
      <img align="absmiddle" height="559px" width="678px" file="ed10003.JPG" alt="圖式IMG-2/Draw/ed10003.JPG" img-content="tif" img-format="tif" orientation="portrait" inline="yes"></img>
    </figure>
    <figure>
      <img align="absmiddle" height="591px" width="697px" file="ed10004.JPG" alt="圖式IMG-2/Draw/ed10004.JPG" img-content="tif" img-format="tif" orientation="portrait" inline="yes"></img>
    </figure>
    <figure>
      <img align="absmiddle" height="582px" width="729px" file="ed10005.JPG" alt="圖式IMG-2/Draw/ed10005.JPG" img-content="tif" img-format="tif" orientation="portrait" inline="yes"></img>
    </figure>
    <figure>
      <img align="absmiddle" height="693px" width="640px" file="ed10006.JPG" alt="圖式IMG-2/Draw/ed10006.JPG" img-content="tif" img-format="tif" orientation="portrait" inline="yes"></img>
    </figure>
    <figure>
      <img align="absmiddle" height="772px" width="642px" file="ed10007.JPG" alt="圖式IMG-2/Draw/ed10007.JPG" img-content="tif" img-format="tif" orientation="portrait" inline="yes"></img>
    </figure>
    <drawing-description>
      <p type="p">
        <p>敬請參閱所附圖式，本創作整體係包括帽體、飾體及鏡片。其中，帽體頂部兩側分別具有梭形條狀之側飾體，於飾體設有複數個呈斜狀之透氣孔及按壓開關，兩側飾體後端係以一平板相互連結，帽體頂部前緣係設有與側飾體呈反向，且為三角狀之前飾體，於該前飾體設有透氣孔及按壓開關，帽體前側係具有鏡片，鏡片兩側分別以圓弧之潤飾與帽體連結。其整體均由弧形線條相互潤飾而成，造型新穎前衛，線條俐落，極具流線美感，配合鏡片向下展開時可使整體外觀形成球狀曲線美感，更使得本創作整體外觀呈現出奇特之意匠風采，予人曲線設計創意之美感。</p>
      </p>
      <p type="p">
        <p>將此安全帽配戴於頭部，以供騎乘機車時保護騎乘者頭部安全，且可藉由飾體之透氣孔構成通風效果，避免頭部之悶熱，使配戴更為舒適。</p>
      </p>
      <p type="p">
        <p>整體觀之，本案無論弧面、飾紋皆潤飾得宜，搭配協調，堪稱一兼具實用性及造型美之設計佳作，由於未曾見有類同創作公開在先，爰依法提出新式樣專利之申請。</p>
      </p>
      <p type="p">
        <p>圖面中之色彩為本案不主張設計之部分。</p>
      </p>
    </drawing-description>
  </drawings>
  <claims />
</tw-patent-grant>

=== JamesTu-jtjt/patent-scraper-tool/example/PatentIsuRegSpecXMLA_041016/101122836.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE tw-patent-grant SYSTEM "patent.dtd">
<tw-patent-grant dtd-version="A103.1.0">
  <tw-bibliographic-data-grant>
    <volno>41</volno>
    <isuno>16</isuno>
    <kindcode>B</kindcode>
    <publication-reference>
      <document-id>
        <doc-number>I439544</doc-number>
        <kind />
        <date>103/06/01</date>
      </document-id>
    </publication-reference>
    <certificate-number>
      <document-id>
        <doc-number>I439544</doc-number>
        <kind />
        <date />
      </document-id>
    </certificate-number>
    <application-reference appl-type="invention">
      <document-id>
        <doc-number>101122836</doc-number>
        <kind />
        <date>101/06/26</date>
      </document-id>
    </application-reference>
    <classification-ipc>
      <main-classification edition="200601120140318V">C12N1/20</main-classification>
    </classification-ipc>
    <parties>
      <applicants>
        <applicant sequence="1" app-type="applicant">
          <addressbook>
            <chinese-name name-type="">
              <last-name>國立高雄海洋科技大學</last-name>
              <first-name></first-name>
            </chinese-name>
            <english-name name-type="">
              <last-name>NATIONAL KAOHSIUNG MARINE UNIVERSITY</last-name>
              <middle-name />
              <first-name />
            </english-name>
            <address>高雄市</address>
            <english-country>TW</english-country>
            <english-address>TW</english-address>
          </addressbook>
        </applicant>
      </applicants>
      <inventors>
        <inventor sequence="1" app-type="applicant">
          <addressbook>
            <chinese-name name-type="">
              <last-name>許德賢</last-name>
              <first-name></first-name>
            </chinese-name>
            <english-name name-type="">
              <last-name>SHEU, DERSHYAN</last-name>
              <middle-name></middle-name>
              <first-name></first-name>
            </english-name>
            <address></address>
            <english-country>TW</english-country>
            <english-address>TW</english-address>
          </addressbook>
        </inventor>
        <inventor sequence="2" app-type="applicant">
          <addressbook>
            <chinese-name name-type="">
              <last-name>林啟燦</last-name>
              <first-name></first-name>
            </chinese-name>
            <english-name name-type="">
              <last-name>LIN, CHITSAN</last-name>
              <middle-name></middle-name>
              <first-name></first-name>
            </english-name>
            <address></address>
            <english-country>TW</english-country>
            <english-address>TW</english-address>
          </addressbook>
        </inventor>
        <inventor sequence="3" app-type="applicant">
          <addressbook>
            <chinese-name name-type="">
              <last-name>賴勇維</last-name>
              <first-name></first-name>
            </chinese-name>
            <english-name name-type="">
              <last-name>LAI, YUNGWEI</last-name>
              <middle-name></middle-name>
              <first-name></first-name>
            </english-name>
            <address></address>
            <english-country>TW</english-country>
            <english-address>TW</english-address>
          </addressbook>
        </inventor>
      </inventors>
      <agents>
        <agent sequence="1" rep-type="agent">
          <addressbook>
            <chinese-name name-type="">
              <last-name>蔡坤財</last-name>
              <first-name></first-name>
            </chinese-name>
            <address>臺北市</address>
          </addressbook>
        </agent>
        <agent sequence="2" rep-type="agent">
          <addressbook>
            <chinese-name name-type="">
              <last-name>李世章</last-name>
              <first-name></first-name>
            </chinese-name>
            <address>臺北市</address>
          </addressbook>
        </agent>
      </agents>
    </parties>
    <examiners>
      <examiner>
        <chinese-name>
          <last-name>施雅儀</last-name>
          <first-name />
        </chinese-name>
      </examiner>
    </examiners>
    <priority-claims></priority-claims>
    <tw-bio-deposit>
      <bio-accno>BCRC 910551</bio-accno>
      <date>20120522</date>
      <depositary>
        <country>TW</country>
        <text>食品工業發展研究所生物資源保存及研究中心</text>
      </depositary>
    </tw-bio-deposit>
    <invention-title>
      <chinese-title>赤球菌分離株及其用於降解油類</chinese-title>
      <english-title>RHODOCOCCUS ISOLATE AND APPLICATION OF DEGRADING OILS</english-title>
    </invention-title>
    <refs>
      <ref>
        <country>US</country>
        <doc-number>2008/0020947</doc-number>
        <kind>A1</kind>
      </ref>
    </refs>
    <orefs>
      <oref>Bell KS et al., "The genus Rhodococcus", Journal of Applied Microbiology, vol.85, p.195-210, 1998                                                                                                                                                                                                                                                                                                               
</oref>
      <oref>Iwabuchi N et al., "Extracellular Polysaccharides of Rhodococcus rhodochrous S-2 Stimulate the Degradation of Aromatic Components in Crude Oil by Indigenous Marine Bacteria", Applied and Environmental Microbiology, vol.68, no.5, p.2337-2343, 2002/05                                                                                                                                                       
</oref>
      <oref>Peng F et al., "An oil-degrading bacterium: Rhodococcus erythropolis strain 3C-9 and its biosurfactants", Journal of Applied Microbiology, vol.102, p.1603-1611, 2007                                                                                                                                                                                                                                           
</oref>
      <oref>Auffret M et al., "Degradation of a Mixture of Hydrocarbons, Gasoline, and Diesel Oil Additives by Rhodococcus aetherivorans and Rhodococcus wratislaviensis", Applied and Environmental Microbiology, vol.75, no.24, p7774-7782, 2009/12                                                                                                                                                                       
</oref>
    </orefs>
    <application-publication-reference>
      <document-id>
        <doc-number>201400610</doc-number>
        <kind />
        <date>103/01/01</date>
      </document-id>
    </application-publication-reference>
  </tw-bibliographic-data-grant>
  <drawings num="第6圖">
    <figure>
      <img align="absmiddle" height="503px" width="574px" file="d10001.TIF" alt="圖式ed10001.png" img-content="tif" img-format="tif" orientation="portrait" inline="yes" giffile="ed10001.png"></img>
    </figure>
    <figure>
      <img align="absmiddle" height="487px" width="568px" file="d10002.TIF" alt="圖式ed10002.png" img-content="tif" img-format="tif" orientation="portrait" inline="yes" giffile="ed10002.png"></img>
    </figure>
    <figure>
      <img align="absmiddle" height="803px" width="627px" file="d10003.TIF" alt="圖式ed10003.png" img-content="tif" img-format="tif" orientation="portrait" inline="yes" giffile="ed10003.png"></img>
    </figure>
    <figure>
      <img align="absmiddle" height="593px" width="984px" file="d10004.TIF" alt="圖式ed10004.png" img-content="tif" img-format="tif" orientation="portrait" inline="yes" giffile="ed10004.png"></img>
    </figure>
    <figure>
      <img align="absmiddle" height="569px" width="979px" file="d10005.TIF" alt="圖式ed10005.png" img-content="tif" img-format="tif" orientation="portrait" inline="yes" giffile="ed10005.png"></img>
    </figure>
    <figure>
      <img align="absmiddle" height="635px" width="760px" file="d10006.TIF" alt="*圖式ed10006.png" img-content="tif" img-format="tif" orientation="portrait" inline="yes" giffile="ed10006.png"></img>
    </figure>
    <drawing-description>
      <p type="p">為讓本發明之上述和其他目的、特徵、優點與實施例能更明顯易懂，所附圖式之說明如下：第1圖係繪示依照本發明之一實施例之赤球菌分離株的生長溫度分析圖。</p>
      <p type="p">第2圖係繪示依照本發明之一實施例之赤球菌分離株的生長pH值分析圖。</p>
      <p type="p">第3圖係繪示依照本發明之一實施例之赤球菌分離株與鄰近菌株之親緣關係樹狀圖。</p>
      <p type="p">第4圖係繪示依照本發明之一實施例之赤球菌分離株的分解柴油能力測試分析圖。</p>
      <p type="p">第5圖係繪示未添加赤球菌分離株的分解柴油能力測試分析圖。</p>
      <p type="p">第6圖係繪示依照本發明之一實施例之赤球菌分離株的分解柴油效率測試分析圖。</p>
    </drawing-description>
  </drawings>
  <claims>
    <claim id="clm1" num="1">
      <p type="claim-text">一種赤球菌分離株，其中該赤球菌(<i>Rhodococcus</i>
sp.)分離株SF-1寄存於臺灣新竹食品工業研究與發展研究所，寄存編號為BCRC 910551。</p>
    </claim>
    <claim id="clm2" num="2">
      <p type="claim-text">一種用於降解油類之組成物，其中該用於降解油類之組成物包括一赤球菌分離株SF-1(寄存編號為BCRC 910551)，且該赤球菌分離株SF-1之含量可有效降解油類。</p>
    </claim>
    <claim id="clm3" num="3">
      <p type="claim-text">根據申請專利範圍第2項所述之用於降解油類之組成物，其中該油類係選自於由燃料用油、食用油以及上述之任意組合所組成之一族群。</p>
    </claim>
    <claim id="clm4" num="4">
      <p type="claim-text">根據申請專利範圍第2項所述之用於降解油類之組成物，其中該油類係選自於由柴油、沙拉油以及上述之任意組合所組成之一族群。</p>
    </claim>
  </claims>
</tw-patent-grant>

=== JamesTu-jtjt/patent-scraper-tool/example/PatentIsuRegSpecXMLA_041016/101130847.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE tw-patent-grant SYSTEM "patent.dtd">
<tw-patent-grant dtd-version="A103.1.0">
  <tw-bibliographic-data-grant>
    <volno>41</volno>
    <isuno>16</isuno>
    <kindcode>B</kindcode>
    <publication-reference>
      <document-id>
        <doc-number>I439549</doc-number>
        <kind />
        <date>103/06/01</date>
      </document-id>
    </publication-reference>
    <certificate-number>
      <document-id>
        <doc-number>I439549</doc-number>
        <kind />
        <date />
      </document-id>
    </certificate-number>
    <application-reference appl-type="invention">
      <document-id>
        <doc-number>101130847</doc-number>
        <kind />
        <date>101/08/24</date>
      </document-id>
    </application-reference>
    <classification-ipc>
      <main-classification edition="200601120140220V">C21C1/10</main-classification>
    </classification-ipc>
    <parties>
      <applicants>
        <applicant sequence="1" app-type="applicant">
          <addressbook>
            <chinese-name name-type="">
              <last-name>石川硅石工業股份有限公司</last-name>
              <first-name></first-name>
            </chinese-name>
            <english-name name-type="">
              <last-name>ISHIKAWALITE INDUSTRY, CO., LTD.</last-name>
              <middle-name />
              <first-name />
            </english-name>
            <address></address>
            <english-country>JP</english-country>
            <english-address>JP</english-address>
          </addressbook>
        </applicant>
      </applicants>
      <inventors>
        <inventor sequence="1" app-type="applicant">
          <addressbook>
            <chinese-name name-type="">
              <last-name>吉川紘平</last-name>
              <first-name></first-name>
            </chinese-name>
            <english-name name-type="">
              <last-name>YOSHIKAWA, KOUHEI</last-name>
              <middle-name></middle-name>
              <first-name></first-name>
            </english-name>
            <address></address>
            <english-country>JP</english-country>
            <english-address>JP</english-address>
          </addressbook>
        </inventor>
      </inventors>
      <agents>
        <agent sequence="1" rep-type="agent">
          <addressbook>
            <chinese-name name-type="">
              <last-name>林志剛</last-name>
              <first-name></first-name>
            </chinese-name>
            <address>臺北市</address>
          </addressbook>
        </agent>
      </agents>
    </parties>
    <examiners>
      <examiner>
        <chinese-name>
          <last-name>呂振榮</last-name>
          <first-name />
        </chinese-name>
      </examiner>
    </examiners>
    <priority-claims>
      <priority-claim sequence="1">
        <country>日本</country>
        <doc-number>2012-152586</doc-number>
        <date>20120706</date>
      </priority-claim>
    </priority-claims>
    <tw-bio-deposit></tw-bio-deposit>
    <invention-title>
      <chinese-title>鑄鐵之石墨球狀化處理時的球狀化劑上部的覆蓋材</chinese-title>
      <english-title />
    </invention-title>
    <refs>
      <ref>
        <country>JP</country>
        <doc-number>55-32761</doc-number>
        <kind>A</kind>
      </ref>
      <ref>
        <country>JP</country>
        <doc-number>56-86652</doc-number>
        <kind>A</kind>
      </ref>
      <ref>
        <country>JP</country>
        <doc-number>4-176810</doc-number>
        <kind>A</kind>
      </ref>
    </refs>
    <application-publication-reference>
      <document-id>
        <doc-number>201402826</doc-number>
        <kind />
        <date>103/01/16</date>
      </document-id>
    </application-publication-reference>
  </tw-bibliographic-data-grant>
  <drawings num="第1圖">
    <figure>
      <img align="absmiddle" height="243px" width="424px" file="ed10001.JPG" alt="*圖式IMG-2/Draw/ed10001.JPG" img-content="tif" img-format="tif" orientation="portrait" inline="yes"></img>
    </figure>
    <figure>
      <img align="absmiddle" height="243px" width="409px" file="ed10002.JPG" alt="圖式IMG-2/Draw/ed10002.JPG" img-content="tif" img-format="tif" orientation="portrait" inline="yes"></img>
    </figure>
    <figure>
      <img align="absmiddle" height="234px" width="406px" file="ed10003.JPG" alt="圖式IMG-2/Draw/ed10003.JPG" img-content="tif" img-format="tif" orientation="portrait" inline="yes"></img>
    </figure>
    <figure>
      <img align="absmiddle" height="243px" width="425px" file="ed10004.JPG" alt="圖式IMG-2/Draw/ed10004.JPG" img-content="tif" img-format="tif" orientation="portrait" inline="yes"></img>
    </figure>
    <drawing-description>
      <p type="p">第1圖是顯示粒子徑為1.7mm~5.0mm之本發明的覆蓋材的熔融鑄鐵的反應後的石墨球狀化的組織照片。</p>
      <p type="p">第2圖是顯示粒子徑為0.1mm~0.3mm之本發明的覆蓋材的熔融鑄鐵的反應後的石墨球狀化的組織照片。</p>
      <p type="p">第3圖是顯示粒子徑為0.1mm以下且0.1~0.3mm(1/1)的本發明的覆蓋材的熔融鑄鐵的反應後的石墨球狀化的組織照片。</p>
      <p type="p">第4圖是顯示使用衝孔碎屑之傳統的覆蓋材的熔融鑄鐵的反應後的石墨球狀化的組織照片。</p>
    </drawing-description>
  </drawings>
  <claims>
    <claim id="clm1" num="1">
      <p type="claim-text">一種鑄鐵之石墨球狀化處理時的球狀化劑上部的覆蓋材，其特徵為：是火山性矽酸鹽礦物，製作成多孔質的粒子，且含有：SiO<sub>2</sub>
為70~75重量%、Al<sub>2</sub>
O<sub>3</sub>
為12~14重量%、K<sub>2</sub>
O為3~5重量%、Na<sub>2</sub>
O為3~4重量%、CaO為0.7~1.5重量%、Fe<sub>2</sub>
O<sub>3</sub>
為1.2~1.5重量%、MgO為0.1~0.2重量%、TiO<sub>2</sub>
為0.05~0.1重量%。</p>
    </claim>
    <claim id="clm2" num="2">
      <p type="claim-text">如申請專利範圍第1項所述的鑄鐵之石墨球狀化處理時的球狀化劑上部的覆蓋材，其比重為0.5~1.0g/cm<sup>3</sup>
，而且是直徑5mm以下的多孔質的粒狀體。</p>
    </claim>
    <claim id="clm3" num="3">
      <p type="claim-text">如申請專利範圍第1或第2項所述的鑄鐵之石墨球狀化處理時的球狀化劑上部的覆蓋材，是將其外形製作成直徑5mm~10mm的球狀，或長度5mm~10mm的棒狀，一旦與鑄鐵的熔融金屬液接觸的話就會被熔解而浮出液面，可促進被設置在下部的石墨球狀化劑的反應。
</p>
    </claim>
    <claim id="clm4" num="4">
      <p type="claim-text">如申請專利範圍第1或第2項所述的鑄鐵之石墨球狀化處理時的球狀化劑上部的覆蓋材，其熔解溫度為1,100~1,200℃，熔解後會浮出液面，會與含有浮游雜質之爐渣結合而具有除滓劑的作用。
</p>
    </claim>
    <claim id="clm5" num="5">
      <p type="claim-text">如申請專利範圍第3項所述的鑄鐵之石墨球狀化處理時的球狀化劑上部的覆蓋材，其熔解溫度為1,100~1,200℃，熔解後會浮出液面，會與含有浮游雜質之爐渣結合而具有除滓劑的作用。
</p>
    </claim>
  </claims>
</tw-patent-grant>
